export const ACTION_TYPE = {
	SET_USER: 'SET_USER',
	LOGOUT: 'LOGOUT',
	ORDER_COUNT: 'ORDER_COUNT',
	BASKET_OPEN: 'BASKET_OPEN',
	FLAG: 'FLAG',
	FLAG_DELETE_REVIEWS: 'FLAG_DELETE_REVIEWS',
	PHRASE_TEXT: 'PHRASE_TEXT',
	COUNT_REVIEWS: 'COUNT_REVIEWS',
	SET_ONGOODS: 'SET_ONGOODS',
	PARAMSID: 'PARAMSID',
	ADDONGOODS_OPEN: 'ADDONGOODS_OPEN',
};
